<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  
  <script>
    // 使用setTimeout进行异步操作,1000ms之后会回调setTimeout函数
    // alt+shift+向下或向上箭头可向下/上复制
    // setTimeout(() => {
    //   console.log('hello world')
    //   console.log('hello world')
    //   console.log('hello world')
    //   console.log('hello world')
    // },1000)

    // 使用promise类进行封装
    // 参数是函数(resolve,reject),这两个函数的参数也是函数
    // 延迟1S打印helloworld ,再延迟1s打印hellovue.js,再延迟1s打印hello
    // 这样的操作就陷入了回调地狱
    // new Promise((resolve,reject) => {
    //   setTimeout(() => {
    //     console.log('hello world')
    //     console.log('hello world')
    //     console.log('hello world')
    //     console.log('hello world')

    //     setTimeout(() => {
    //       console.log('hello vue.js')
    //       console.log('hello vue.js')
    //       console.log('hello vue.js')
    //       console.log('hello vue.js')

    //       setTimeout(() => {
    //         console.log('hello')
    //         console.log('hello')
    //         console.log('hello')
    //         console.log('hello')
    //       },1000)
    //     },1000)
    //   },1000)
    // })



    // 为了避免上述这种回调地狱，需要将里面的东西给抽取出来
    // 内部调用resolve()函数，当调用该函数时，函数会去到.then中去执行,then的参数也是一个函数
    // new Promise((resolve,reject) => {
    //   setTimeout(() =>{
    //     resolve()
    //   },1000)
    // }).then(() => {
    //     console.log('hello world')
    //     console.log('hello world')
    //     console.log('hello world')
    //     console.log('hello world')

    //   // 通过返回一个Promise值
    //     return new Promise((resolve,reject) => {
    //       setTimeout(() => {
    //         resolve()
    //       },1000)
    //     }).then(() => {
    //       console.log('hello vue.js')
    //       console.log('hello vue.js')
    //       console.log('hello vue.js')
    //       console.log('hello vue.js')

    //       return new Promise((resolve,reject) => {
    //         setTimeout(() => {
    //           resolve()
    //         },1000)
    //       }).then(() => {
    //         console.log('hello')
    //         console.log('hello')
    //         console.log('hello')
    //         console.log('hello')
    //       })
    //     })
    // })



// 注意，应该是这种形式，
// 链式编程
// 即new Promise().then(   return new Promise())  .then(  return new Promise()).then()
// 上面的那种形式变成了then嵌套了，虽然同样能正确展示，应该也是变成回调地狱的一种了？？？？
    // new Promise((resolve,reject) => {
    //   // 第一次网络请求的代码
    //   setTimeout(() =>{
    //     resolve()
    //   },1000)
    // }).then(() => {
    //   // 第一次拿到结果的处理代码
    //   console.log('hello world')
    //   console.log('hello world')
    //   console.log('hello world')
    //   console.log('hello world')

    //   // 通过返回一个Promise值
    //   return new Promise((resolve,reject) => {
    //     // 第二次网络请求的代码
    //     setTimeout(() => {
    //       resolve()
    //     },1000)
    //   })
    // }).then(() => {
    //   // 第二次拿到结果的处理代码
    //   console.log('hello vue.js')
    //   console.log('hello vue.js')
    //   console.log('hello vue.js')
    //   console.log('hello vue.js')

    //   return new Promise((resolve,reject) => {
    //     // 第三次网络请求的代码
    //     setTimeout(() => {
    //       resolve()
    //     },1000)
    //   })
    // }).then(() => {
    //   // 第三次结果处理
    //   console.log('hello')
    //   console.log('hello')
    //   console.log('hello')
    //   console.log('hello')
    // },1000)


// 什么情况下会用到promise
//    一旦有异步操作时，就可以将其塞到promise里，异步请求后调用一下resolve方法，别人
//    就可以在then方法中进行操作
      // 简单来说，即一般情况下，当有异步操作时，使用promise对这个即将进行的异步操作进行封装
      //其中流程：new的时候，类似于一个构造函数
                    // （1、保存了一些状态信息  2、执行传入的函数） 
      // 并且例如从网络请求中传过来一些数据时，不要直接在异步请求（如setTimeout函数中）进行操作
      // 而是通过在异步请求中调用resolve()或reject()函数，通过这两个参数函数，数据会自动传递到
      // 后面的.then()函数或.catch()函数中，你可以在then()/catch()函数中操作传过来的数据，简洁明了
new Promise((resolve,reject) => {
  setTimeout(() => {
    // 成功的时候调用resolve,表示解决，进入.then()表示下一步
    // resolve('Hello')

    // 失败的时候调用reject,表示拒绝，进入.catch()表示捕获，捕获异常等
    reject('error message')
  },1000)
}).then((data) => {     //这里的data就是resolve中传过来的参数，有时setTimeout中含有参数data,
  // 这里将打印Hello字符串，因为从resolve传入的是Hello
  console.log(data)      //也可以通过resolve(data),数据会自动作为传入函数then的参数.then(data)
}).catch(err => {
  // 这里打印error message字符串，因为从reject传入的是字符串'error message'
  console.log(err)        
})


// 总而言之，promise是为了写代码更优雅
  </script>
</body>
</html>